baseURL = 'https://sairpa.github.io/blog/'
languageCode = 'en-us'
title = "Ajay's blog"
theme = 'hugo-book'

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

uglyURLs = true

[params]
  BookTitle = "Ajay's blog"
  BookTheme = 'auto'
  BookSearch = true
  BookSection = 'notes'

[markup.goldmark.renderer]
  unsafe = true
